### PR TITLE
Adding callbacks for general purpose events.

### PR DESCRIPTION
**Pull request by vivekg342**
javascript-state-machine has general purpose events.

These could be useful when doing something generic on all transitions.

### CODE REVIEW

**Comment by vstirbu** [comment]
This is a good addition! 

Wouldn't be more intuitive to have the common hooks using `on{leave|enter|entered}` convention? State is not needed as they apply to any state.

ps: test are missing

**Comment by vivekg342** [comment]
Sounds good. Let me write some tests and push them in this reques.t

**Comment by vivekg342** [comment]
Renamed to on{leave|enter|entered} 
Also modified a few cases to test these global events.

**Comment by vstirbu** [comment]
new version published in npm

**Pull request merged**
