### PR TITLE
experimental fsm-as-promised built with composable factories

### PR DESCRIPTION
**Pull request by boneskull**
- includes EventEmitter implementation
- all tests pass (no breaking changes)
- stampit includes lodash as a dependency anyway, so I included it.

This is just for you to take a look at and maybe give you some ideas.  But if you like it and want to merge it, be my guest :smile:

Because we're not hiding so much functionality within closures, it's easier to customize its behavior.

My suggestion is to just examine `index.js` instead of trying to digest a diff; code has been moved around, but basically it's entirely rewritten.

### CODE REVIEW

**Comment by boneskull** [comment]
Given you may not be familiar with stampit, it gives you *composable factory functions* instead of classes.  The nature of these is that you can modify them at will:

```js
var StateMachine = require('fsm-as-promised').StateMachine;

var MyStateMachine = StateMachine
  .static({FSMError: SomeOtherErrorConstructor})
  .methods({
    foo: function() {
      // do something
    }
  });

var myFsm = MyStateMachine({events: {}, callbacks: {});

// or

var MyFactory = stampit({
  // "constructor"
  init: function init() {
    this.foo = 'bar';
  }
}).compose(StateMachine);

var myThing = MyFactory({events: {}, callbacks: {});
myThing.foo // bar
myThing.current // none
```

**Comment by boneskull** [comment]
FWIW, I'm using fsm-as-promised in a rewrite of Mocha, which heavily consumes stampit.  Indeed, I'm wrapping `StateMachine` in a factory:

```js
'use strict';

import StateMachine from 'fsm-as-promised';
import stampit from 'stampit';
import {pick, flatten, startsWith} from 'lodash/fp';
import is from 'check-more-types';
import assert from 'lazy-ass';

const getStateMachineProps = pick([
  'events',
  'callbacks',
  'initial',
  'final'
]);

const startsWithOn = startsWith('on');

const isBasicEvent = is.schema({
  name: is.unemptyString,
  from: is.or(is.unemptyString, is.arrayOfUnemptyStrings),
  to: is.maybe.unemptyString
});

const isConditionalEvent = is.schema({
  name: is.unemptyString,
  from: is.or(is.unemptyString, is.arrayOfUnemptyStrings),
  to: is.arrayOfUnemptyStrings,
  condition: is.function
});

const isEvent = is.or(isBasicEvent, isConditionalEvent);

const FSM = stampit({
  refs: {
    callbacks: {}
  },
  props: {
    events: []
  },
  init () {
    StateMachine(getStateMachineProps(this), this);
  },
  static: {
    initial (state) {
      assert(is.unemptyString(state));
      return this.props({initial: state});
    },
    final (...args) {
      args = flatten(args);
      assert(is.arrayOfUnemptyStrings(args));
      return this.props({final: args});
    },
    events (...args) {
      args = flatten(args);
      assert(is.arrayOf(isEvent, args));
      return this.props({events: this.fixed.props.events.concat(args)});
    },
    event (obj) {
      assert(isEvent(obj));
      return this.props({events: this.fixed.props.events.concat(obj)});
    },
    callback (name, func) {
      assert(is.unemptyString(name));
      assert(is.function(func));
      if (!startsWithOn(name)) {
        name = `on${name}`;
      }
      name = name.toLowerCase();
      const callbacks = Object.assign({},
        this.fixed.refs.callbacks,
        {[name]: func});
      return this.refs({callbacks});
    },
    callbacks (obj) {
      assert(is.object(obj));
      // TODO validate
      const callbacks = Object.assign({}, this.fixed.refs.callbacks, obj);
      return this.refs({callbacks});
    }
  }
});

export default FSM;

```

I can use it like so:

```js
const Thing = FSM
  .initial('foo')
  .final(['bar', 'baz'])
  .event({name: 'myEvent', from: 'foo', to: 'bar'});

const myThingInstance = Thing();
```

**Comment by boneskull** [comment]
in particular, each instance of `Test` is composed from an FSM.

**Comment by vstirbu** [comment]
Yes, I like it!

Now that this is such a big change, implementation wise, it might be a good time to do also some breaking changes such as:
* eliminate leading `on` from callbacks,
* rely on the browser/node build in Promise implementation as default and manually provide one if the environment does not have one.

**Comment by vstirbu** [comment]
Also published in npm.

**Comment by vstirbu** [comment]
This is getting better and better... so, I might be wrong, but having the FSM compassable will enable plugins. For example, I was wondering that the conditional transition could be implemented as a plugin...

**Comment by vstirbu** [comment]
@boneskull can you provide a test for this situation: https://coveralls.io/jobs/12786956/source_files/35296975#L404

**Comment by boneskull** [comment]
see #16

**Pull request merged**
